// Code generated by scripts/generate.mjs from spec/openapi.yml; DO NOT EDIT.

package avee

import "context"

var generatedCalls = []generatedCall{
	{
		operation: "x402Discovery",
		response:  "X402Discovery",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.X402Discovery(ctx)
		},
	},
	{
		operation: "status",
		response:  "StatusResponse",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Status(ctx)
		},
	},
	{
		operation: "key",
		response:  "KeyInfo",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Key(ctx)
		},
	},
	{
		operation: "config",
		response:  "Config",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Config(ctx)
		},
	},
	{
		operation: "chains",
		response:  "ChainList",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Chains(ctx)
		},
	},
	{
		operation: "search",
		response:  "SearchResponse",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Search(ctx, SearchParams{Q: "eth", Chains: []ChainSlug{"base"}, Limit: Ptr(int32(5))})
		},
	},
	{
		operation: "pairs",
		response:  "PairPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Pairs(ctx, PairsParams{Chains: []ChainSlug{"base"}, Q: Ptr("eth"), Protocols: []FactoryType{"x"}, DexNames: []string{"x"}, MinLiquidityUSD: Ptr(0.5), MaxLiquidityUSD: Ptr(0.5), MinAPR: Ptr(0.5), MaxAPR: Ptr(0.5), MinScore: Ptr(uint32(5)), MaxScore: Ptr(uint32(5)), MinAgeSeconds: Ptr(uint32(5)), MaxAgeSeconds: Ptr(uint32(5)), MarketType: Ptr(MarketType("any")), OnlyTrustable: Ptr(true), MaxDeployedPairs: Ptr(uint32(5)), Sort: Ptr(SortBy("liquidity")), Order: Ptr(OrderBy("asc")), Timeframe: Ptr(TimeFrame("5m")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "pair",
		response:  "PairInfo",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Pair(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "pairTrades",
		response:  "TradePage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PairTrades(ctx, "base", "0x00000000000000000000000000000000000000a1", PairTradesParams{TxType: []TxType{"all"}, Maker: Ptr("0x00000000000000000000000000000000000000a1"), From: Ptr(int64(5)), To: Ptr(int64(5)), Order: Ptr(OrderBy("asc")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "pairCandles",
		response:  "ChartCandles",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PairCandles(ctx, "base", "0x00000000000000000000000000000000000000a1", PairCandlesParams{Res: "1", From: 5, To: 5, Countback: Ptr(int64(5)), Currency: Ptr("usd"), PriceFromQuote: Ptr(true), VolumeFromQuote: Ptr(true)})
		},
	},
	{
		operation: "trending",
		response:  "PairPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Trending(ctx, TrendingParams{Chains: []ChainSlug{"base"}, Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "pairsNew",
		response:  "PairPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PairsNew(ctx, PairsNewParams{Chain: "base", MinLiquidityUSD: Ptr(0.5), MaxAgeSeconds: Ptr(uint32(5)), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "launchpadTokens",
		response:  "PairPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.LaunchpadTokens(ctx, LaunchpadTokensParams{Chain: "base", LaunchStatus: Ptr(LaunchStatus("new")), Launchpads: []string{"x"}, Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "pairBatch",
		response:  "PairBatchResponse",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PairBatch(ctx, PairBatchRequest{Items: []PairBatchRef{PairBatchRef{Chain: "base", Address: "0x00000000000000000000000000000000000000a1"}}})
		},
	},
	{
		operation: "perps",
		response:  "PairPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Perps(ctx, PerpsParams{Chains: []ChainSlug{"base"}, Q: Ptr("eth"), Sort: Ptr(PerpSortBy("volume")), Order: Ptr(OrderBy("asc")), Timeframe: Ptr(TimeFrame("5m")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "perpHistory",
		response:  "PerpHistory",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PerpHistory(ctx, "BTC", PerpHistoryParams{Chain: Ptr("base"), From: Ptr(int64(5)), To: Ptr(int64(5)), Interval: Ptr("5m")})
		},
	},
	{
		operation: "perpLiquidations",
		response:  "PerpLiquidations",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PerpLiquidations(ctx, PerpLiquidationsParams{Chain: Ptr("base"), Market: Ptr("BTC"), From: Ptr(int64(5)), To: Ptr(int64(5))})
		},
	},
	{
		operation: "deployerTokens",
		response:  "DeployerLaunchPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeployerTokens(ctx, "0x00000000000000000000000000000000000000a1", DeployerTokensParams{Chains: []ChainSlug{"base"}, Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "tokenByAddress",
		response:  "TokenInfo",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenByAddress(ctx, "base", "0x00000000000000000000000000000000000000a1", TokenByAddressParams{IncludeInstances: Ptr(true), IncludeMarket: Ptr(true)})
		},
	},
	{
		operation: "tokenPairs",
		response:  "PairPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenPairs(ctx, "base", "0x00000000000000000000000000000000000000a1", TokenPairsParams{Limit: Ptr(int32(5))})
		},
	},
	{
		operation: "tokenVerdict",
		response:  "TokenVerdict",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenVerdict(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "tokenVerdictProof",
		response:  "TokenVerdictProof",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenVerdictProof(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "tokenBrief",
		response:  "TokenBrief",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenBrief(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "tokenByID",
		response:  "TokenInfo",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenByID(ctx, "0190f5a0-0000-7000-8000-000000000001", TokenByIDParams{IncludeInstances: Ptr(true), IncludeMarket: Ptr(true)})
		},
	},
	{
		operation: "tokenBySlug",
		response:  "TokenInfo",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenBySlug(ctx, "wrapped-ether", TokenBySlugParams{IncludeInstances: Ptr(true), IncludeMarket: Ptr(true)})
		},
	},
	{
		operation: "tokens",
		response:  "TokenPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Tokens(ctx, TokensParams{Q: Ptr("eth"), Chains: []ChainSlug{"base"}, Categories: []string{"x"}, Sort: Ptr(TokenSortBy("market_cap")), Order: Ptr(OrderBy("asc")), MinLiquidityUSD: Ptr(0.5), MaxLiquidityUSD: Ptr(0.5), MinVolumeUSD: Ptr(0.5), MaxVolumeUSD: Ptr(0.5), MinMarketCapUSD: Ptr(0.5), MaxMarketCapUSD: Ptr(0.5), MinFDVUSD: Ptr(0.5), MaxFDVUSD: Ptr(0.5), MinAgeSeconds: Ptr(uint32(5)), MaxAgeSeconds: Ptr(uint32(5)), MinScore: Ptr(uint32(5)), MaxScore: Ptr(uint32(5)), MinHolders: Ptr(uint32(5)), MaxHolders: Ptr(uint32(5)), IncludeInstances: Ptr(true), IncludeMarket: Ptr(true), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "tokenBatch",
		response:  "TokenBatchResponse",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenBatch(ctx, TokenBatchRequest{Items: []TokenBatchRef{TokenBatchRef{Chain: "base", Address: "0x00000000000000000000000000000000000000a1"}}})
		},
	},
	{
		operation: "tokenHolders",
		response:  "TokenHolderPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenHolders(ctx, "base", "0x00000000000000000000000000000000000000a1", TokenHoldersParams{Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "tokenTraders",
		response:  "TokenTraderPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.TokenTraders(ctx, "base", "0x00000000000000000000000000000000000000a1", TokenTradersParams{Sort: Ptr(TokenTraderSortBy("realized_pnl")), State: Ptr(PositionState("any")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "farms",
		response:  "FarmPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Farms(ctx, FarmsParams{Chains: []ChainSlug{"base"}, Q: Ptr("eth"), Factories: []Address{"0x00000000000000000000000000000000000000a1"}, Sort: Ptr(FarmSortBy("tvl")), Order: Ptr(OrderBy("asc")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "farm",
		response:  "FarmInfo",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Farm(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "wallets",
		response:  "WalletPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Wallets(ctx, WalletsParams{Chain: "base", Window: Ptr(WalletWindow("1d")), Sort: Ptr(WalletSortBy("total_pnl")), Order: Ptr(OrderBy("asc")), MinTotalPnlUSD: Ptr(0.5), MinRealizedPnlUSD: Ptr(0.5), MinVolumeUSD: Ptr(0.5), MinWinRate: Ptr(0.5), MinTrades: Ptr(uint32(5)), MaxAvgHoldSeconds: Ptr(int64(5)), MinUserScore: Ptr(uint32(5)), NoAbuseEvidence: Ptr(true), OnlyCopyEligible: Ptr(true), ExcludeBots: Ptr(true), Tiers: []WalletTier{"x"}, Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "walletStats",
		response:  "WalletStats",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletStats(ctx, WalletStatsParams{Chains: []ChainSlug{"base"}})
		},
	},
	{
		operation: "walletLabelsBatch",
		response:  "WalletLabelList",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletLabelsBatch(ctx, WalletLabelsRequest{Chain: "base", Addresses: []Address{"0x00000000000000000000000000000000000000a1"}})
		},
	},
	{
		operation: "walletOverview",
		response:  "WalletOverview",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletOverview(ctx, "0x00000000000000000000000000000000000000a1", WalletOverviewParams{Chains: []ChainSlug{"base"}, Window: Ptr(WalletWindow("1d"))})
		},
	},
	{
		operation: "leaderboard",
		response:  "Leaderboard",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Leaderboard(ctx, LeaderboardParams{Scope: "chains", Chain: Ptr("base"), Chains: []ChainSlug{"base"}, Seasonal: Ptr(true), Season: Ptr(int32(5)), Limit: Ptr(int32(5))})
		},
	},
	{
		operation: "walletProfile",
		response:  "WalletProfile",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletProfile(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "walletPositions",
		response:  "WalletPositionPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletPositions(ctx, "base", "0x00000000000000000000000000000000000000a1", WalletPositionsParams{State: Ptr(PositionState("any")), Sort: Ptr(PositionSortBy("token")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "walletTrades",
		response:  "WalletTradePage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletTrades(ctx, "base", "0x00000000000000000000000000000000000000a1", WalletTradesParams{Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "walletChart",
		response:  "WalletChart",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletChart(ctx, "base", "0x00000000000000000000000000000000000000a1", WalletChartParams{Window: Ptr(WalletWindow("1d"))})
		},
	},
	{
		operation: "walletBestTrades",
		response:  "WalletBestTrades",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletBestTrades(ctx, "base", "0x00000000000000000000000000000000000000a1", WalletBestTradesParams{Window: Ptr(WalletWindow("1d")), Limit: Ptr(int32(5))})
		},
	},
	{
		operation: "walletRounds",
		response:  "WalletRoundPage",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletRounds(ctx, "base", "0x00000000000000000000000000000000000000a1", WalletRoundsParams{Token: Ptr("0x00000000000000000000000000000000000000a1"), State: Ptr(PositionState("any")), Limit: Ptr(int32(5)), Cursor: Ptr("c1")})
		},
	},
	{
		operation: "walletFunding",
		response:  "WalletFunding",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.WalletFunding(ctx, "base", "0x00000000000000000000000000000000000000a1")
		},
	},
	{
		operation: "oraclePrices",
		response:  "OraclePriceList",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.OraclePrices(ctx, OraclePricesParams{Ids: []string{"abababababababababababababababababababababababababababababababab"}})
		},
	},
	{
		operation: "oraclePricesAt",
		response:  "OraclePriceList",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.OraclePricesAt(ctx, OraclePricesAtParams{Ids: []string{"abababababababababababababababababababababababababababababababab"}, Ts: 5})
		},
	},
}
