// Code generated by scripts/generate.mjs from spec/openapi.yml; DO NOT EDIT.

package avee

import (
	"context"
	"iter"
	"math"
)

type SearchParams struct {
	Q      string
	Chains []ChainSlug
	Limit  *int32
}

type PairsParams struct {
	Chains           []ChainSlug
	Q                *string
	Protocols        []FactoryType
	DexNames         []string
	MinLiquidityUSD  *float64
	MaxLiquidityUSD  *float64
	MinAPR           *float64
	MaxAPR           *float64
	MinScore         *uint32
	MaxScore         *uint32
	MinAgeSeconds    *uint32
	MaxAgeSeconds    *uint32
	MarketType       *MarketType
	OnlyTrustable    *bool
	MaxDeployedPairs *uint32
	Sort             *SortBy
	Order            *OrderBy
	Timeframe        *TimeFrame
	Limit            *int32
	Cursor           *string
}

type PairTradesParams struct {
	TxType []TxType
	Maker  *Address
	From   *int64
	To     *int64
	Order  *OrderBy
	Limit  *int32
	Cursor *string
}

type PairCandlesParams struct {
	Res             ResolutionType
	From            int64
	To              int64
	Countback       *int64
	Currency        *string
	PriceFromQuote  *bool
	VolumeFromQuote *bool
}

type TrendingParams struct {
	Chains []ChainSlug
	Limit  *int32
	Cursor *string
}

type PairsNewParams struct {
	Chain           string
	MinLiquidityUSD *float64
	MaxAgeSeconds   *uint32
	Limit           *int32
	Cursor          *string
}

type LaunchpadTokensParams struct {
	Chain        string
	LaunchStatus *LaunchStatus
	Launchpads   []string
	Limit        *int32
	Cursor       *string
}

type PerpsParams struct {
	Chains    []ChainSlug
	Q         *string
	Sort      *PerpSortBy
	Order     *OrderBy
	Timeframe *TimeFrame
	Limit     *int32
	Cursor    *string
}

type PerpHistoryParams struct {
	Chain    *string
	From     *int64
	To       *int64
	Interval *string
}

type PerpLiquidationsParams struct {
	Chain  *string
	Market *Address
	From   *int64
	To     *int64
}

type DeployerTokensParams struct {
	Chains []ChainSlug
	Limit  *int32
	Cursor *string
}

type TokenByAddressParams struct {
	IncludeInstances *bool
	IncludeMarket    *bool
}

type TokenPairsParams struct {
	Limit *int32
}

type TokenByIDParams struct {
	IncludeInstances *bool
	IncludeMarket    *bool
}

type TokenBySlugParams struct {
	IncludeInstances *bool
	IncludeMarket    *bool
}

type TokensParams struct {
	Q                *string
	Chains           []ChainSlug
	Categories       []string
	Sort             *TokenSortBy
	Order            *OrderBy
	MinLiquidityUSD  *float64
	MaxLiquidityUSD  *float64
	MinVolumeUSD     *float64
	MaxVolumeUSD     *float64
	MinMarketCapUSD  *float64
	MaxMarketCapUSD  *float64
	MinFDVUSD        *float64
	MaxFDVUSD        *float64
	MinAgeSeconds    *uint32
	MaxAgeSeconds    *uint32
	MinScore         *uint32
	MaxScore         *uint32
	MinHolders       *uint32
	MaxHolders       *uint32
	IncludeInstances *bool
	IncludeMarket    *bool
	Limit            *int32
	Cursor           *string
}

type TokenHoldersParams struct {
	Limit  *int32
	Cursor *string
}

type TokenTradersParams struct {
	Sort   *TokenTraderSortBy
	State  *PositionState
	Limit  *int32
	Cursor *string
}

type FarmsParams struct {
	Chains    []ChainSlug
	Q         *string
	Factories []Address
	Sort      *FarmSortBy
	Order     *OrderBy
	Limit     *int32
	Cursor    *string
}

type WalletsParams struct {
	Chain             string
	Window            *WalletWindow
	Sort              *WalletSortBy
	Order             *OrderBy
	MinTotalPnlUSD    *float64
	MinRealizedPnlUSD *float64
	MinVolumeUSD      *float64
	MinWinRate        *float64
	MinTrades         *uint32
	MaxAvgHoldSeconds *int64
	MinUserScore      *uint32
	NoAbuseEvidence   *bool
	OnlyCopyEligible  *bool
	ExcludeBots       *bool
	Tiers             []WalletTier
	Limit             *int32
	Cursor            *string
}

type WalletStatsParams struct {
	Chains []ChainSlug
}

type WalletOverviewParams struct {
	Chains []ChainSlug
	Window *WalletWindow
}

type LeaderboardParams struct {
	Scope    LeaderboardScope
	Chain    *string
	Chains   []ChainSlug
	Seasonal *bool
	Season   *int32
	Limit    *int32
}

type WalletPositionsParams struct {
	State  *PositionState
	Sort   *PositionSortBy
	Limit  *int32
	Cursor *string
}

type WalletTradesParams struct {
	Limit  *int32
	Cursor *string
}

type WalletChartParams struct {
	Window *WalletWindow
}

type WalletBestTradesParams struct {
	Window *WalletWindow
	Limit  *int32
}

type WalletRoundsParams struct {
	Token  *Address
	State  *PositionState
	Limit  *int32
	Cursor *string
}

type OraclePricesParams struct {
	Ids []string
}

type OraclePricesAtParams struct {
	Ids []string
	Ts  int64
}

func (c *Client) X402Discovery(ctx context.Context) (*X402Discovery, error) {
	r := newCall("x402Discovery", "GET")
	r.pathLiteral(".well-known")
	r.pathLiteral("x402")

	var out X402Discovery
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Status(ctx context.Context) (*StatusResponse, error) {
	r := newCall("status", "GET")
	r.pathLiteral("status")

	var out StatusResponse
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Key(ctx context.Context) (*KeyInfo, error) {
	r := newCall("key", "GET")
	r.pathLiteral("key")

	var out KeyInfo
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Config(ctx context.Context) (*Config, error) {
	r := newCall("config", "GET")
	r.pathLiteral("config")

	var out Config
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Chains(ctx context.Context) (*ChainList, error) {
	r := newCall("chains", "GET")
	r.pathLiteral("chains")

	var out ChainList
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Search(ctx context.Context, params SearchParams) (*SearchResponse, error) {
	r := newCall("search", "GET")
	r.pathLiteral("search")
	strQ(r, "q", &params.Q, 1, 128, true, false)
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	intQ(r, "limit", params.Limit, 1, 50)

	var out SearchResponse
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Pairs(ctx context.Context, params PairsParams) (*PairPage, error) {
	r := newCall("pairs", "GET")
	r.pathLiteral("pairs")
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	strQ(r, "q", params.Q, 0, 128, false, false)
	listQ(r, "protocols", params.Protocols, 0, 32, 0, -1, false)
	listQ(r, "dex_names", params.DexNames, 0, 32, 0, 64, false)
	floatQ(r, "min_liquidity_usd", params.MinLiquidityUSD, 0, math.Inf(1))
	floatQ(r, "max_liquidity_usd", params.MaxLiquidityUSD, 0, math.Inf(1))
	floatQ(r, "min_apr", params.MinAPR, math.Inf(-1), math.Inf(1))
	floatQ(r, "max_apr", params.MaxAPR, math.Inf(-1), math.Inf(1))
	intQ(r, "min_score", params.MinScore, 0, 100)
	intQ(r, "max_score", params.MaxScore, 0, 100)
	intQ(r, "min_age_seconds", params.MinAgeSeconds, 0, noMax)
	intQ(r, "max_age_seconds", params.MaxAgeSeconds, 0, noMax)
	strQ(r, "market_type", params.MarketType, 0, -1, false, false)
	boolQ(r, "only_trustable", params.OnlyTrustable)
	intQ(r, "max_deployed_pairs", params.MaxDeployedPairs, 1, noMax)
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	strQ(r, "order", params.Order, 0, -1, false, false)
	strQ(r, "timeframe", params.Timeframe, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out PairPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterPairs(ctx context.Context, params PairsParams) iter.Seq2[PairInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]PairInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.Pairs(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) Pair(ctx context.Context, chain, address string) (*PairInfo, error) {
	r := newCall("pair", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("pairs")
	r.pathParam("address", address, 1, 128, false)

	var out PairInfo
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) PairTrades(ctx context.Context, chain, address string, params PairTradesParams) (*TradePage, error) {
	r := newCall("pairTrades", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("pairs")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("trades")
	listQ(r, "tx_type", params.TxType, 0, 8, 0, -1, false)
	strQ(r, "maker", params.Maker, 1, 128, false, false)
	intQ(r, "from", params.From, 0, noMax)
	intQ(r, "to", params.To, 0, noMax)
	strQ(r, "order", params.Order, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out TradePage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterPairTrades(ctx context.Context, chain, address string, params PairTradesParams) iter.Seq2[Transaction, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]Transaction, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.PairTrades(ctx, chain, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) PairCandles(ctx context.Context, chain, address string, params PairCandlesParams) (*ChartCandles, error) {
	r := newCall("pairCandles", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("pairs")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("candles")
	strQ(r, "res", &params.Res, 1, -1, true, false)
	intQ(r, "from", &params.From, 0, noMax)
	intQ(r, "to", &params.To, 0, noMax)
	intQ(r, "countback", params.Countback, 1, 5000)
	strQ(r, "currency", params.Currency, 0, -1, false, false)
	boolQ(r, "price_from_quote", params.PriceFromQuote)
	boolQ(r, "volume_from_quote", params.VolumeFromQuote)

	var out ChartCandles
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Trending(ctx context.Context, params TrendingParams) (*PairPage, error) {
	r := newCall("trending", "GET")
	r.pathLiteral("trending")
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out PairPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterTrending(ctx context.Context, params TrendingParams) iter.Seq2[PairInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]PairInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.Trending(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) PairsNew(ctx context.Context, params PairsNewParams) (*PairPage, error) {
	r := newCall("pairsNew", "GET")
	r.pathLiteral("pairs")
	r.pathLiteral("new")
	strQ(r, "chain", &params.Chain, 1, 32, true, false)
	floatQ(r, "min_liquidity_usd", params.MinLiquidityUSD, 0, math.Inf(1))
	intQ(r, "max_age_seconds", params.MaxAgeSeconds, 0, noMax)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out PairPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterPairsNew(ctx context.Context, params PairsNewParams) iter.Seq2[PairInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]PairInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.PairsNew(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) LaunchpadTokens(ctx context.Context, params LaunchpadTokensParams) (*PairPage, error) {
	r := newCall("launchpadTokens", "GET")
	r.pathLiteral("launchpads")
	r.pathLiteral("tokens")
	strQ(r, "chain", &params.Chain, 1, 32, true, false)
	strQ(r, "launch_status", params.LaunchStatus, 0, -1, false, false)
	listQ(r, "launchpads", params.Launchpads, 0, 32, 0, 64, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out PairPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterLaunchpadTokens(ctx context.Context, params LaunchpadTokensParams) iter.Seq2[PairInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]PairInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.LaunchpadTokens(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) PairBatch(ctx context.Context, body PairBatchRequest) (*PairBatchResponse, error) {
	r := newCall("pairBatch", "POST")
	r.pathLiteral("pairs")
	r.pathLiteral("batch")
	r.checkItems("items", len(body.Items), 1, 50)
	r.body = body

	var out PairBatchResponse
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Perps(ctx context.Context, params PerpsParams) (*PairPage, error) {
	r := newCall("perps", "GET")
	r.pathLiteral("perps")
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	strQ(r, "q", params.Q, 0, 128, false, false)
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	strQ(r, "order", params.Order, 0, -1, false, false)
	strQ(r, "timeframe", params.Timeframe, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out PairPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterPerps(ctx context.Context, params PerpsParams) iter.Seq2[PairInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]PairInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.Perps(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) PerpHistory(ctx context.Context, market string, params PerpHistoryParams) (*PerpHistory, error) {
	r := newCall("perpHistory", "GET")
	r.pathLiteral("perps")
	r.pathParam("market", market, 1, 128, false)
	r.pathLiteral("history")
	strQ(r, "chain", params.Chain, 1, 32, false, false)
	intQ(r, "from", params.From, 0, noMax)
	intQ(r, "to", params.To, 0, noMax)
	strQ(r, "interval", params.Interval, 0, -1, false, false)

	var out PerpHistory
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) PerpLiquidations(ctx context.Context, params PerpLiquidationsParams) (*PerpLiquidations, error) {
	r := newCall("perpLiquidations", "GET")
	r.pathLiteral("perps")
	r.pathLiteral("liquidations")
	strQ(r, "chain", params.Chain, 1, 32, false, false)
	strQ(r, "market", params.Market, 1, 128, false, false)
	intQ(r, "from", params.From, 0, noMax)
	intQ(r, "to", params.To, 0, noMax)

	var out PerpLiquidations
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) DeployerTokens(ctx context.Context, address string, params DeployerTokensParams) (*DeployerLaunchPage, error) {
	r := newCall("deployerTokens", "GET")
	r.pathLiteral("deployers")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("tokens")
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out DeployerLaunchPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterDeployerTokens(ctx context.Context, address string, params DeployerTokensParams) iter.Seq2[PairInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]PairInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.DeployerTokens(ctx, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) TokenByAddress(ctx context.Context, chain, address string, params TokenByAddressParams) (*TokenInfo, error) {
	r := newCall("tokenByAddress", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	boolQ(r, "include_instances", params.IncludeInstances)
	boolQ(r, "include_market", params.IncludeMarket)

	var out TokenInfo
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenPairs(ctx context.Context, chain, address string, params TokenPairsParams) (*PairPage, error) {
	r := newCall("tokenPairs", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("pairs")
	intQ(r, "limit", params.Limit, 1, 10)

	var out PairPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenVerdict(ctx context.Context, chain, address string) (*TokenVerdict, error) {
	r := newCall("tokenVerdict", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("verdict")

	var out TokenVerdict
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenVerdictProof(ctx context.Context, chain, address string) (*TokenVerdictProof, error) {
	r := newCall("tokenVerdictProof", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("proof")

	var out TokenVerdictProof
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenBrief(ctx context.Context, chain, address string) (*TokenBrief, error) {
	r := newCall("tokenBrief", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("brief")

	var out TokenBrief
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenByID(ctx context.Context, id string, params TokenByIDParams) (*TokenInfo, error) {
	r := newCall("tokenByID", "GET")
	r.pathLiteral("tokens")
	r.pathParam("id", id, 1, -1, true)
	boolQ(r, "include_instances", params.IncludeInstances)
	boolQ(r, "include_market", params.IncludeMarket)

	var out TokenInfo
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenBySlug(ctx context.Context, slug string, params TokenBySlugParams) (*TokenInfo, error) {
	r := newCall("tokenBySlug", "GET")
	r.pathLiteral("tokens")
	r.pathLiteral("by-slug")
	r.pathParam("slug", slug, 1, 128, false)
	boolQ(r, "include_instances", params.IncludeInstances)
	boolQ(r, "include_market", params.IncludeMarket)

	var out TokenInfo
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Tokens(ctx context.Context, params TokensParams) (*TokenPage, error) {
	r := newCall("tokens", "GET")
	r.pathLiteral("tokens")
	strQ(r, "q", params.Q, 0, 128, false, false)
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	listQ(r, "categories", params.Categories, 0, 32, 1, 64, false)
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	strQ(r, "order", params.Order, 0, -1, false, false)
	floatQ(r, "min_liquidity_usd", params.MinLiquidityUSD, 0, math.Inf(1))
	floatQ(r, "max_liquidity_usd", params.MaxLiquidityUSD, 0, math.Inf(1))
	floatQ(r, "min_volume_usd", params.MinVolumeUSD, 0, math.Inf(1))
	floatQ(r, "max_volume_usd", params.MaxVolumeUSD, 0, math.Inf(1))
	floatQ(r, "min_market_cap_usd", params.MinMarketCapUSD, 0, math.Inf(1))
	floatQ(r, "max_market_cap_usd", params.MaxMarketCapUSD, 0, math.Inf(1))
	floatQ(r, "min_fdv_usd", params.MinFDVUSD, 0, math.Inf(1))
	floatQ(r, "max_fdv_usd", params.MaxFDVUSD, 0, math.Inf(1))
	intQ(r, "min_age_seconds", params.MinAgeSeconds, 0, noMax)
	intQ(r, "max_age_seconds", params.MaxAgeSeconds, 0, noMax)
	intQ(r, "min_score", params.MinScore, 0, 100)
	intQ(r, "max_score", params.MaxScore, 0, 100)
	intQ(r, "min_holders", params.MinHolders, 0, noMax)
	intQ(r, "max_holders", params.MaxHolders, 0, noMax)
	boolQ(r, "include_instances", params.IncludeInstances)
	boolQ(r, "include_market", params.IncludeMarket)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out TokenPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterTokens(ctx context.Context, params TokensParams) iter.Seq2[TokenInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]TokenInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.Tokens(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) TokenBatch(ctx context.Context, body TokenBatchRequest) (*TokenBatchResponse, error) {
	r := newCall("tokenBatch", "POST")
	r.pathLiteral("tokens")
	r.pathLiteral("batch")
	r.checkItems("items", len(body.Items), 1, 200)
	r.body = body

	var out TokenBatchResponse
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) TokenHolders(ctx context.Context, chain, address string, params TokenHoldersParams) (*TokenHolderPage, error) {
	r := newCall("tokenHolders", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("holders")
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out TokenHolderPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterTokenHolders(ctx context.Context, chain, address string, params TokenHoldersParams) iter.Seq2[TokenHolder, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]TokenHolder, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.TokenHolders(ctx, chain, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) TokenTraders(ctx context.Context, chain, address string, params TokenTradersParams) (*TokenTraderPage, error) {
	r := newCall("tokenTraders", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("tokens")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("traders")
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	strQ(r, "state", params.State, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out TokenTraderPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterTokenTraders(ctx context.Context, chain, address string, params TokenTradersParams) iter.Seq2[TokenTrader, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]TokenTrader, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.TokenTraders(ctx, chain, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) Farms(ctx context.Context, params FarmsParams) (*FarmPage, error) {
	r := newCall("farms", "GET")
	r.pathLiteral("farms")
	listQ(r, "chains", params.Chains, 1, 8, 1, 32, true)
	strQ(r, "q", params.Q, 0, 128, false, false)
	listQ(r, "factories", params.Factories, 0, 32, 1, 128, false)
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	strQ(r, "order", params.Order, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out FarmPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterFarms(ctx context.Context, params FarmsParams) iter.Seq2[FarmInfo, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]FarmInfo, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.Farms(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) Farm(ctx context.Context, chain, address string) (*FarmInfo, error) {
	r := newCall("farm", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("farms")
	r.pathParam("address", address, 1, 128, false)

	var out FarmInfo
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Wallets(ctx context.Context, params WalletsParams) (*WalletPage, error) {
	r := newCall("wallets", "GET")
	r.pathLiteral("wallets")
	strQ(r, "chain", &params.Chain, 1, 32, true, false)
	strQ(r, "window", params.Window, 0, -1, false, false)
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	strQ(r, "order", params.Order, 0, -1, false, false)
	floatQ(r, "min_total_pnl_usd", params.MinTotalPnlUSD, math.Inf(-1), math.Inf(1))
	floatQ(r, "min_realized_pnl_usd", params.MinRealizedPnlUSD, math.Inf(-1), math.Inf(1))
	floatQ(r, "min_volume_usd", params.MinVolumeUSD, math.Inf(-1), math.Inf(1))
	floatQ(r, "min_win_rate", params.MinWinRate, 0, 1)
	intQ(r, "min_trades", params.MinTrades, noMin, noMax)
	intQ(r, "max_avg_hold_seconds", params.MaxAvgHoldSeconds, noMin, noMax)
	intQ(r, "min_user_score", params.MinUserScore, 0, 100)
	boolQ(r, "no_abuse_evidence", params.NoAbuseEvidence)
	boolQ(r, "only_copy_eligible", params.OnlyCopyEligible)
	boolQ(r, "exclude_bots", params.ExcludeBots)
	listQ(r, "tiers", params.Tiers, 0, 8, 0, 32, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out WalletPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterWallets(ctx context.Context, params WalletsParams) iter.Seq2[WalletListItem, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]WalletListItem, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.Wallets(ctx, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) WalletStats(ctx context.Context, params WalletStatsParams) (*WalletStats, error) {
	r := newCall("walletStats", "GET")
	r.pathLiteral("wallets")
	r.pathLiteral("stats")
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)

	var out WalletStats
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) WalletLabelsBatch(ctx context.Context, body WalletLabelsRequest) (*WalletLabelList, error) {
	r := newCall("walletLabelsBatch", "POST")
	r.pathLiteral("wallets")
	r.pathLiteral("labels")
	r.pathLiteral("batch")
	r.checkItems("addresses", len(body.Addresses), 1, 200)
	r.body = body

	var out WalletLabelList
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) WalletOverview(ctx context.Context, address string, params WalletOverviewParams) (*WalletOverview, error) {
	r := newCall("walletOverview", "GET")
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("overview")
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	strQ(r, "window", params.Window, 0, -1, false, false)

	var out WalletOverview
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) Leaderboard(ctx context.Context, params LeaderboardParams) (*Leaderboard, error) {
	r := newCall("leaderboard", "GET")
	r.pathLiteral("leaderboard")
	strQ(r, "scope", &params.Scope, 1, -1, true, false)
	strQ(r, "chain", params.Chain, 1, 32, false, false)
	listQ(r, "chains", params.Chains, 0, 32, 1, 32, false)
	boolQ(r, "seasonal", params.Seasonal)
	intQ(r, "season", params.Season, 0, noMax)
	intQ(r, "limit", params.Limit, 1, 200)

	var out Leaderboard
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) WalletProfile(ctx context.Context, chain, address string) (*WalletProfile, error) {
	r := newCall("walletProfile", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)

	var out WalletProfile
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) WalletPositions(ctx context.Context, chain, address string, params WalletPositionsParams) (*WalletPositionPage, error) {
	r := newCall("walletPositions", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("positions")
	strQ(r, "state", params.State, 0, -1, false, false)
	strQ(r, "sort", params.Sort, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out WalletPositionPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterWalletPositions(ctx context.Context, chain, address string, params WalletPositionsParams) iter.Seq2[WalletPosition, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]WalletPosition, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.WalletPositions(ctx, chain, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) WalletTrades(ctx context.Context, chain, address string, params WalletTradesParams) (*WalletTradePage, error) {
	r := newCall("walletTrades", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("trades")
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out WalletTradePage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterWalletTrades(ctx context.Context, chain, address string, params WalletTradesParams) iter.Seq2[WalletTrade, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]WalletTrade, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.WalletTrades(ctx, chain, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) WalletChart(ctx context.Context, chain, address string, params WalletChartParams) (*WalletChart, error) {
	r := newCall("walletChart", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("chart")
	strQ(r, "window", params.Window, 0, -1, false, false)

	var out WalletChart
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) WalletBestTrades(ctx context.Context, chain, address string, params WalletBestTradesParams) (*WalletBestTrades, error) {
	r := newCall("walletBestTrades", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("best-trades")
	strQ(r, "window", params.Window, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)

	var out WalletBestTrades
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) WalletRounds(ctx context.Context, chain, address string, params WalletRoundsParams) (*WalletRoundPage, error) {
	r := newCall("walletRounds", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("rounds")
	strQ(r, "token", params.Token, 1, 128, false, false)
	strQ(r, "state", params.State, 0, -1, false, false)
	intQ(r, "limit", params.Limit, 1, 100)
	strQ(r, "cursor", params.Cursor, 0, 512, false, false)

	var out WalletRoundPage
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) IterWalletRounds(ctx context.Context, chain, address string, params WalletRoundsParams) iter.Seq2[WalletPositionRound, error] {
	return paginate(ctx, params.Cursor, func(cursor *string) ([]WalletPositionRound, *string, error) {
		p := params
		p.Cursor = cursor

		page, err := c.WalletRounds(ctx, chain, address, p)
		if err != nil {
			return nil, nil, err
		}

		return page.Items, page.NextCursor, nil
	})
}

func (c *Client) WalletFunding(ctx context.Context, chain, address string) (*WalletFunding, error) {
	r := newCall("walletFunding", "GET")
	r.pathLiteral("chains")
	r.pathParam("chain", chain, 1, 32, false)
	r.pathLiteral("wallets")
	r.pathParam("address", address, 1, 128, false)
	r.pathLiteral("funding")

	var out WalletFunding
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) OraclePrices(ctx context.Context, params OraclePricesParams) (*OraclePriceList, error) {
	r := newCall("oraclePrices", "GET")
	r.pathLiteral("prices")
	listQ(r, "ids", params.Ids, 1, 100, 64, 66, true)

	var out OraclePriceList
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

func (c *Client) OraclePricesAt(ctx context.Context, params OraclePricesAtParams) (*OraclePriceList, error) {
	r := newCall("oraclePricesAt", "GET")
	r.pathLiteral("prices")
	r.pathLiteral("at")
	listQ(r, "ids", params.Ids, 1, 100, 64, 66, true)
	intQ(r, "ts", &params.Ts, 1, noMax)

	var out OraclePriceList
	if err := c.do(ctx, r, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
